//
//  Updater.swift
//  CleanYourBoard - Keyboard Cleaner
//
//  Thin wrapper around Sparkle so the rest of the app stays decoupled.
//  The `#if canImport(Sparkle)` guard lets the project keep building
//  before the SPM dependency is added in Xcode. Once Sparkle is on the
//  path the full implementation activates automatically.
//
//  How to wire Sparkle in Xcode (one-time):
//    1. File → Add Package Dependencies…
//    2. URL:  https://github.com/sparkle-project/Sparkle
//    3. Dependency Rule: Up to Next Major Version, 2.0.0
//    4. Add to target: CleanYourBoard - Keyboard Cleaner
//
//  Info.plist requirements (already in Info.plist):
//    SUFeedURL       https://r0cketbean.github.io/CleanYourBoard/appcast.xml
//    SUPublicEDKey   <generated by Sparkle's generate_keys tool>
//
//  Plus this class also returns the feed URL via SPUUpdaterDelegate so
//  Sparkle has a redundant source — useful as belt-and-braces.
//

import AppKit
import Foundation
import Observation
import SwiftUI

#if canImport(Sparkle)
import Sparkle
#endif

/// The single source of truth for the update feed URL. Both the
/// Info.plist key and the SPUUpdaterDelegate fallback reference this value.
enum UpdateFeed {
    static let urlString = "https://r0cketbean.github.io/CleanYourBoard/appcast.xml"
}

@MainActor
@Observable
final class UpdaterController: NSObject {

    /// Whether the user can trigger a manual update check right now.
    /// (Sparkle disables the menu item while a check is already in flight.)
    private(set) var canCheckForUpdates: Bool = true

    /// True when Sparkle is actually wired into the build.
    let isAvailable: Bool

    #if canImport(Sparkle)
    private var updaterController: SPUStandardUpdaterController!
    private var observation: NSKeyValueObservation?
    #endif

    override init() {
        #if canImport(Sparkle)
        isAvailable = true
        #else
        isAvailable = false
        #endif

        super.init()

        #if canImport(Sparkle)
        updaterController = SPUStandardUpdaterController(
            startingUpdater: true,
            updaterDelegate: self,
            userDriverDelegate: nil
        )
        observation = updaterController.updater.observe(
            \.canCheckForUpdates,
            options: [.initial, .new]
        ) { [weak self] updater, _ in
            Task { @MainActor [weak self] in
                self?.canCheckForUpdates = updater.canCheckForUpdates
            }
        }
        #endif
    }

    func checkForUpdates() {
        #if canImport(Sparkle)
        updaterController.checkForUpdates(nil)
        #endif
    }
}

#if canImport(Sparkle)
extension UpdaterController: SPUUpdaterDelegate {
    nonisolated func feedURLString(for updater: SPUUpdater) -> String? {
        UpdateFeed.urlString
    }
}
#endif
