//
//  Updater.swift
//  CleanYourBoard - Keyboard Cleaner
//
//  Thin wrapper around Sparkle so the rest of the app can stay decoupled.
//  The `#if canImport(Sparkle)` guard lets the project keep building before
//  the SPM dependency is added in Xcode. Once Sparkle is on the path the
//  full implementation activates automatically.
//
//  How to wire Sparkle in Xcode (one-time):
//    1. File → Add Package Dependencies…
//    2. URL:  https://github.com/sparkle-project/Sparkle
//    3. Dependency Rule: Up to Next Major Version, 2.0.0
//    4. Add to target: CleanYourBoard - Keyboard Cleaner
//
//  After that, set these Info.plist keys (see RELEASE.md):
//    SUFeedURL       https://r0cketbean.github.io/CleanYourBoard/appcast.xml
//    SUPublicEDKey   <generated by Sparkle's generate_keys tool>
//

import Foundation
import Observation
import SwiftUI

#if canImport(Sparkle)
import Sparkle
#endif

@MainActor
@Observable
final class UpdaterController {

    /// Whether the user can trigger a manual update check at this very moment.
    /// (Sparkle disables the menu item while a check is already in flight.)
    private(set) var canCheckForUpdates: Bool = true

    /// True when Sparkle is actually wired into the build.
    /// Lets the UI hide the "Check for Updates" button gracefully during dev
    /// before the SPM package has been added.
    let isAvailable: Bool

    #if canImport(Sparkle)
    private let updaterController: SPUStandardUpdaterController
    private var observation: NSKeyValueObservation?
    #endif

    init() {
        #if canImport(Sparkle)
        updaterController = SPUStandardUpdaterController(
            startingUpdater: true,
            updaterDelegate: nil,
            userDriverDelegate: nil
        )
        isAvailable = true
        observation = updaterController.updater.observe(
            \.canCheckForUpdates,
            options: [.initial, .new]
        ) { [weak self] updater, _ in
            Task { @MainActor [weak self] in
                self?.canCheckForUpdates = updater.canCheckForUpdates
            }
        }
        #else
        isAvailable = false
        #endif
    }

    func checkForUpdates() {
        #if canImport(Sparkle)
        updaterController.checkForUpdates(nil)
        #endif
    }
}
